### ISSUE TITLE
LED Roulette references external content?

### ISSUE THREAD

**Issue by RandomInsano** [rust-embedded/discovery#126] opened 2018-10-14 03:58 UTC
Awash with broken images, this one really stood out:

```<img title="Serial module" src="/assets/serial.jpg">```

I'm not sure if we want to include this with the other book assets or not.

**Comment by adamgreen** [comment] 2018-10-30 05:35
I think this is a duplicate of https://github.com/rust-embedded/bookshelf/issues/4

**Comment by adamgreig** [comment] 2018-10-31 20:31
Thanks!

**Closed by adamgreig** 2018-10-31 20:31 UTC
